import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import SessionProviderWrapper from './SessionProviderWrapper'
import Link from 'next/link'
import { UserAvatar } from '@/components/user-nav'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Header() {
  return (
    <header className="w-full border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50 px-6">
      <nav className="flex h-16 items-center justify-between gap-6 w-full">
        <div className="flex items-center gap-6">
          <Link href="/focus-tracker" className="text-lg font-semibold">
            Focus Tracker
          </Link>
          <Link href="/weight-tracker" className="text-lg font-semibold">
            Weight Tracker
          </Link>
        </div>
        <div className="flex items-center">
          <UserAvatar />
        </div>
      </nav>
    </header>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          themes={['dark', 'light']}
        >
          <SessionProviderWrapper>
            <Header />
            {children}
          </SessionProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  )
}
